schema = 3

[mod]
  [mod."cloud.google.com/go/compute"]
    version = "v1.23.0"
    hash = "sha256-Pd5tMfeatH7p/Mh4b5qUqE9vMDgwwTg6/3Hb8uFZyUw="
  [mod."cloud.google.com/go/compute/metadata"]
    version = "v0.2.3"
    hash = "sha256-kYB1FTQRdTDqCqJzSU/jJYbVUGyxbkASUKbEs36FUyU="
  [mod."cloud.google.com/go/iam"]
    version = "v1.1.1"
    hash = "sha256-VANDj1f2Ckjco+l0KG4uboPE5i2xbbclvZGCojqWepc="
  [mod."cloud.google.com/go/secretmanager"]
    version = "v1.11.1"
    hash = "sha256-5oEXQy/z24V6k/OinEMKWKZYuGIDEZF07fU7Z7aMjlY="
  [mod."github.com/attestantio/go-eth2-client"]
    version = "v0.18.1"
    hash = "sha256-Wgm7u/apiSo8YX3qsdzfwfytWsfe6n62r7WRtOHzW8M="
  [mod."github.com/aws/aws-sdk-go"]
    version = "v1.44.317"
    hash = "sha256-W+6USiZKFIIunoZHnmCyPIIG2JyxJFG/3CtPXIRexRA="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/cenkalti/backoff/v4"]
    version = "v4.2.1"
    hash = "sha256-CKogmPe0pCcAdpztzPwr24rLTJZfq8QVZ9AUduwAcoA="
  [mod."github.com/cespare/xxhash"]
    version = "v1.1.0"
    hash = "sha256-nVDTtXH9PC3yJ0THaQZEN243UP9xgLi/clt5xRqj3+M="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.2.0"
    hash = "sha256-nPufwYQfTkyrEkbBrpqM3C2vnMxfIz6tAaBmiUP7vd4="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/dgraph-io/badger/v2"]
    version = "v2.2007.4"
    hash = "sha256-+KwqZJZpViv8S3TqUVvPXrFoMgWFyS3NoLsi4RR5fGk="
  [mod."github.com/dgraph-io/ristretto"]
    version = "v0.1.1"
    hash = "sha256-Wr9ovXhGi71+n37EnrpIj2o9goyaQHtY4Vvurv6IVlY="
  [mod."github.com/dgryski/go-farm"]
    version = "v0.0.0-20200201041132-a6ae2369ad13"
    hash = "sha256-aOMlPwFY36bLiiIx4HonbCYRAhagk5N6HAWN7Ygif+E="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.1"
    hash = "sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc="
  [mod."github.com/fatih/color"]
    version = "v1.15.0"
    hash = "sha256-7b+scFVQeEUoXfeCDd8X2gS8GMoWA+HxjK8wfbypa5s="
  [mod."github.com/ferranbt/fastssz"]
    version = "v0.1.3"
    hash = "sha256-MJiJ7EfVkBYCopnznP3v1nlVNdcD55/zIclyfMO9KnA="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.6.0"
    hash = "sha256-DQesOCweQPEwmAn6s7DCP/Dwy8IypC+osbpfsvpkdP0="
  [mod."github.com/go-logr/logr"]
    version = "v1.2.4"
    hash = "sha256-+FhzmqKsAnsra5p8LuxENXJBHSeuWjQG8Tzhpyd/ps4="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/goccy/go-yaml"]
    version = "v1.11.0"
    hash = "sha256-ZC3WYiBE8DjyK7DrGG/XoB6Jgh1KqrkQWwFASRzoEts="
  [mod."github.com/golang/glog"]
    version = "v1.1.1"
    hash = "sha256-lzIGeY7v/vAN1/ym3FHTtMO5lSVeqcFbEcXceu3fz+M="
  [mod."github.com/golang/groupcache"]
    version = "v0.0.0-20210331224755-41bb18bfe9da"
    hash = "sha256-7Gs7CS9gEYZkbu5P4hqPGBpeGZWC64VDwraSKFF+VR0="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.3"
    hash = "sha256-svogITcP4orUIsJFjMtp+Uv1+fKJv2Q5Zwf2dMqnpOQ="
  [mod."github.com/golang/snappy"]
    version = "v0.0.4"
    hash = "sha256-Umx+5xHAQCN/Gi4HbtMhnDCSPFAXSsjVbXd8n5LhjAA="
  [mod."github.com/google/go-cmp"]
    version = "v0.5.9"
    hash = "sha256-lQc4O00R3QSMGs9LP8Sy7A9kj0cqV5rrUdpnGeipIyg="
  [mod."github.com/google/s2a-go"]
    version = "v0.1.4"
    hash = "sha256-amTAj6SNERMPxAA43KrzwYgu6GMooayfHCsdkoTI17c="
  [mod."github.com/google/uuid"]
    version = "v1.3.0"
    hash = "sha256-QoR55eBtA94T2tBszyxfDtO7/pjZZSGb5vm7U0Xhs0Y="
  [mod."github.com/googleapis/enterprise-certificate-proxy"]
    version = "v0.2.5"
    hash = "sha256-+Ege2AtPnjJmD6ZmP1osKADCHOAJaMnTOLveNxdoWs8="
  [mod."github.com/googleapis/gax-go/v2"]
    version = "v2.12.0"
    hash = "sha256-ZcXS+1B11UaJHf8D15N3ZCh00fiMUncpHd+eNRffLZ4="
  [mod."github.com/grpc-ecosystem/go-grpc-middleware"]
    version = "v1.4.0"
    hash = "sha256-0UymBjkg41C9MPqkBLz/ZY9WbimZrabpJk+8C/X63h8="
  [mod."github.com/grpc-ecosystem/grpc-gateway/v2"]
    version = "v2.16.2"
    hash = "sha256-FV3V63Y5a7eQmalvwq0CtWjduS20MhmVH1i8A3XWHuU="
  [mod."github.com/hashicorp/hcl"]
    version = "v1.0.0"
    hash = "sha256-xsRCmYyBfglMxeWUvTZqkaRLSW+V2FvNodEDjTGg1WA="
  [mod."github.com/herumi/bls-eth-go-binary"]
    version = "v1.31.0"
    hash = "sha256-aU2NN6xprqhBRiw77YY8ILHKLPcOtwX8Fdjd62H3vm0="
  [mod."github.com/jackc/puddle"]
    version = "v1.3.0"
    hash = "sha256-aFwLmhfgccvygDtvq5N89xZmH3FaRHKC6bzwJvvBAg0="
  [mod."github.com/jmespath/go-jmespath"]
    version = "v0.4.0"
    hash = "sha256-xpT9g2qIXmPq7eeHUXHiDqJeQoHCudh44G/KCSFbcuo="
  [mod."github.com/klauspost/compress"]
    version = "v1.16.7"
    hash = "sha256-8miX/lnXyNLPSqhhn5BesLauaIAxETpQpWtr1cu2f+0="
  [mod."github.com/klauspost/cpuid/v2"]
    version = "v2.2.5"
    hash = "sha256-/M8CHNah2/EPr0va44r1Sx+3H6E+jN8bGFi5jQkLBrM="
  [mod."github.com/magiconair/properties"]
    version = "v1.8.7"
    hash = "sha256-XQ2bnc2s7/IH3WxEO4GishZurMyKwEclZy1DXg+2xXc="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.19"
    hash = "sha256-wYQqGxeqV3Elkmn26Md8mKZ/viw598R4Ych3vtt72YE="
  [mod."github.com/matttproud/golang_protobuf_extensions"]
    version = "v1.0.4"
    hash = "sha256-uovu7OycdeZ2oYQ7FhVxLey5ZX3T0FzShaRldndyGvc="
  [mod."github.com/minio/sha256-simd"]
    version = "v1.0.1"
    hash = "sha256-4hfGDIQaWq8fvtGzHDhoK9v2IocXnJY7OAL6saMJbmA="
  [mod."github.com/mitchellh/go-homedir"]
    version = "v1.1.0"
    hash = "sha256-oduBKXHAQG8X6aqLEpqZHs5DOKe84u6WkBwi4W6cv3k="
  [mod."github.com/mitchellh/mapstructure"]
    version = "v1.5.0"
    hash = "sha256-ztVhGQXs67MF8UadVvG72G3ly0ypQW0IRDdOOkjYwoE="
  [mod."github.com/opentracing/opentracing-go"]
    version = "v1.2.0"
    hash = "sha256-kKTKFGXOsCF6QdVzI++GgaRzv2W+kWq5uDXOJChvLxM="
  [mod."github.com/pelletier/go-toml/v2"]
    version = "v2.0.9"
    hash = "sha256-mLpNBZOK72qPpForSmzQkDrqR5xzmpUdM/0XxB2AYFA="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.16.0"
    hash = "sha256-P/b4/8m1ztF0fCLSJ+eRXN74Bncx2vjOJx7nFl2QEg4="
  [mod."github.com/prometheus/client_model"]
    version = "v0.4.0"
    hash = "sha256-4P0sPWpxa69gGM6zm3dA06cH6twaeopq22VVDJjucHA="
  [mod."github.com/prometheus/common"]
    version = "v0.44.0"
    hash = "sha256-8n3gSWKDSJtGfOQgxsiCGyTnUjb5hvSxJi/hPcrE5Oo="
  [mod."github.com/prometheus/procfs"]
    version = "v0.11.1"
    hash = "sha256-yphZ7NZtYC/tb0HVag2T58SuN64Ial9sBo/TdCEQx6Q="
  [mod."github.com/prysmaticlabs/go-bitfield"]
    version = "v0.0.0-20210809151128-385d8c5e3fb7"
    hash = "sha256-I/QHIqkeSNZxNZrPSoO3UrsvqJ5983U0fys/RePsEcc="
  [mod."github.com/rs/zerolog"]
    version = "v1.30.0"
    hash = "sha256-fOJEpuiJmsp9ONqvmPGOyoBEDfJHBfUH8liiRCWDe1E="
  [mod."github.com/shibukawa/configdir"]
    version = "v0.0.0-20170330084843-e180dbdc8da0"
    hash = "sha256-PzGScp+zkXigokBdOox3UUV1fH1ai9nQdxFAPmVSdW0="
  [mod."github.com/spf13/afero"]
    version = "v1.9.5"
    hash = "sha256-+XECQxkx0P+ZaQDm4dQ6ItMtHMj+2uNemEC18dsdor0="
  [mod."github.com/spf13/cast"]
    version = "v1.5.1"
    hash = "sha256-/tQNGGQv+Osp+2jepQaQe6GlncZbqdxzSR82FieiUBU="
  [mod."github.com/spf13/jwalterweatherman"]
    version = "v1.1.0"
    hash = "sha256-62BQtqTLF/eVrTOr7pUXE7AiHRjOVC8jQs3/Ehmflfs="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/spf13/viper"]
    version = "v1.16.0"
    hash = "sha256-TgBr1SBMaus1oAlA5Kn+iNUJfQCMyo0hT/xFaA7hreQ="
  [mod."github.com/stretchr/testify"]
    version = "v1.8.4"
    hash = "sha256-MoOmRzbz9QgiJ+OOBo5h5/LbilhJfRUryvzHJmXAWjo="
  [mod."github.com/subosito/gotenv"]
    version = "v1.4.2"
    hash = "sha256-LnrDR1k/AoCFWBMcU7vQsoQLkZ65evT2hoQHLDudTsg="
  [mod."github.com/wealdtech/eth2-signer-api"]
    version = "v1.7.1"
    hash = "sha256-R7LDVbdl1pasDjrZ0Y7nc/FFh2kCo/o+nmgaS5NGNKI="
  [mod."github.com/wealdtech/go-bytesutil"]
    version = "v1.2.1"
    hash = "sha256-xI+oOr/PWyD9IH+OkJncH9EI1aqNSVtHV3Xxu207Tls="
  [mod."github.com/wealdtech/go-ecodec"]
    version = "v1.1.4"
    hash = "sha256-I8hLGVDyBSC1SFmppcSLlRqAiUXrQCEJNFYoT5KP7wk="
  [mod."github.com/wealdtech/go-eth2-types/v2"]
    version = "v2.8.2"
    hash = "sha256-j+OM1y4kWlPRopIOHISTXAjMpuPmH1fRnzlRIQsh5nQ="
  [mod."github.com/wealdtech/go-eth2-util"]
    version = "v1.8.2"
    hash = "sha256-WjtJN8z/p4yp27Jhn3bcO2KuGUn3hSsMWFVGVKwMGzo="
  [mod."github.com/wealdtech/go-eth2-wallet"]
    version = "v1.16.0"
    hash = "sha256-s74LG0YS3IBF09/x792sSscSUI9D4xApc2pxc/xyDBU="
  [mod."github.com/wealdtech/go-eth2-wallet-distributed"]
    version = "v1.2.1"
    hash = "sha256-NIIsEzYcAqrEz43XeI/NshF39c9U8DZJIY15TDK8+bw="
  [mod."github.com/wealdtech/go-eth2-wallet-encryptor-keystorev4"]
    version = "v1.4.1"
    hash = "sha256-doak59ssqkovym802xdwYrYEwJP3eBVnEiwrV2FXwkM="
  [mod."github.com/wealdtech/go-eth2-wallet-hd/v2"]
    version = "v2.7.0"
    hash = "sha256-7yygzVRnI3RCWgyJQB0hdYUCWRA+DqdG47g14r6j5Hc="
  [mod."github.com/wealdtech/go-eth2-wallet-nd/v2"]
    version = "v2.5.0"
    hash = "sha256-NsefXdjO1UwCCELGQf3pMO/3uTGa89BUM2s9oyu7nyU="
  [mod."github.com/wealdtech/go-eth2-wallet-store-filesystem"]
    version = "v1.18.1"
    hash = "sha256-b5Uc5NxsG381wA7+Bhq5ZX3Oi7lND05KbZJY8TJL57g="
  [mod."github.com/wealdtech/go-eth2-wallet-store-s3"]
    version = "v1.12.0"
    hash = "sha256-BByo6LHQQORtBWu6BqJkNzq3a6ddebxG2xnl+RvzPMs="
  [mod."github.com/wealdtech/go-eth2-wallet-store-scratch"]
    version = "v1.7.2"
    hash = "sha256-Jz5Ba9sOCo+laFPq2Y+rerJfZYMDPzFwCo/AsOael10="
  [mod."github.com/wealdtech/go-eth2-wallet-types/v2"]
    version = "v2.11.0"
    hash = "sha256-aZ+kljtJ0fJNRhnn6bjqxh9+YG4k9O7uK4UU4gkgfoY="
  [mod."github.com/wealdtech/go-indexer"]
    version = "v1.1.0"
    hash = "sha256-q013dvhhpiEoW2kaErgHoqFB5EyzLlEmP+8jNx0ZK4U="
  [mod."github.com/wealdtech/go-majordomo"]
    version = "v1.1.1"
    hash = "sha256-rsKrkpEXlIGGMB6TVwkMkAUh8QPoIiVocUdWVbnqq1w="
  [mod."go.opencensus.io"]
    version = "v0.24.0"
    hash = "sha256-4H+mGZgG2c9I1y0m8avF4qmt8LUKxxVsTqR8mKgP4yo="
  [mod."go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc"]
    version = "v0.42.0"
    hash = "sha256-NwPfqZadAcHvJNKKpegU3q4daoWxLDmmMC9BavV+7DU="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.16.0"
    hash = "sha256-tOn85qd55FoyzM6v162t15L0Kkxb0pzyOaCh/2HaVcE="
  [mod."go.opentelemetry.io/otel/exporters/otlp/internal/retry"]
    version = "v1.16.0"
    hash = "sha256-gy5ay8amiShRZhfemxxYKekzof0OSK5tRrKjFkTnwHs="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace"]
    version = "v1.16.0"
    hash = "sha256-nYF/Nv7EJruQaXbDsbLOzHVk/ji/NUaE8gMB3TZAP+c="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"]
    version = "v1.16.0"
    hash = "sha256-K5TCv/ITVckxAtwmKeQK5WNo/CzIAgMrA93fy549qlI="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.16.0"
    hash = "sha256-wl64wdxrQlHnXOK8HpPoH4xUE59DJ4nrAO2/yuzmgD0="
  [mod."go.opentelemetry.io/otel/sdk"]
    version = "v1.16.0"
    hash = "sha256-EPdo5t2OK6XBAcsV92RRXTU8CbbEdO9wcfG3oAPfki4="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.16.0"
    hash = "sha256-14YQtLnMYjjt1AlAg1CTQmQflZ+IAp48kqQghZKDXn8="
  [mod."go.opentelemetry.io/proto/otlp"]
    version = "v1.0.0"
    hash = "sha256-w2WbhXXshdm/ZmZkg5VpWwXFLjJRBBwSObyHGjJcELQ="
  [mod."golang.org/x/crypto"]
    version = "v0.12.0"
    hash = "sha256-Wes72EA9ICTG8o0nEYWZk9xjpqlniorFeY6o26GExns="
  [mod."golang.org/x/net"]
    version = "v0.14.0"
    hash = "sha256-QScKgO7lBWOsd0Y31wLRzFETv3tjqdB/eRQWW5q7aV4="
  [mod."golang.org/x/oauth2"]
    version = "v0.11.0"
    hash = "sha256-ztz1lRVZXq6lTN/q4b4Y+P6L1EkP8ZJuhUbSJ0QvCw4="
  [mod."golang.org/x/sync"]
    version = "v0.3.0"
    hash = "sha256-bCJKLvwExhYacH2ZrWlZ38lr1d6oNenNt2m1QqDCs0o="
  [mod."golang.org/x/sys"]
    version = "v0.11.0"
    hash = "sha256-g/LjhABK2c/u6v7M2aAIrHvZjmx/ikGHkef86775N38="
  [mod."golang.org/x/text"]
    version = "v0.12.0"
    hash = "sha256-aNQaW3EgCK9ehpnBzIAkZX6TmiUU1S175YlJUH7P5Qg="
  [mod."golang.org/x/xerrors"]
    version = "v0.0.0-20220907171357-04be3eba64a2"
    hash = "sha256-6+zueutgefIYmgXinOflz8qGDDDj0Zhv+2OkGhBTKno="
  [mod."google.golang.org/api"]
    version = "v0.134.0"
    hash = "sha256-G5pAyyiAQYbwrg319AxP8RB3vraBDVaplgGXFQLExmU="
  [mod."google.golang.org/appengine"]
    version = "v1.6.7"
    hash = "sha256-zIxGRHiq4QBvRqkrhMGMGCaVL4iM4TtlYpAi/hrivS4="
  [mod."google.golang.org/genproto"]
    version = "v0.0.0-20230803162519-f966b187b2e5"
    hash = "sha256-OZHnOp5lPfVy70LEBNdaMqlLjoJZdTkLAZODmvWRqJE="
  [mod."google.golang.org/genproto/googleapis/api"]
    version = "v0.0.0-20230803162519-f966b187b2e5"
    hash = "sha256-J5jdWPiLpWSEVkEghxbQaCb1CG0HqodshHOr/7yw1x0="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20230803162519-f966b187b2e5"
    hash = "sha256-HyfjBmpZdolOTPdQhzoTkHsCProHohXQIu/Nat5pAbA="
  [mod."google.golang.org/grpc"]
    version = "v1.57.0"
    hash = "sha256-hP6alxFu+pcLI4gT3idzEMYNp+DbU3P4xhkpIqGCPXg="
  [mod."google.golang.org/protobuf"]
    version = "v1.31.0"
    hash = "sha256-UdIk+xRaMfdhVICvKRk1THe3R1VU+lWD8hqoW/y8jT0="
  [mod."gopkg.in/ini.v1"]
    version = "v1.67.0"
    hash = "sha256-V10ahGNGT+NLRdKUyRg1dos5RxLBXBk1xutcnquc/+4="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
